### PR TITLE
Implementation of authentication by `firebase`

### PR DESCRIPTION
**Pull request by Parth-Hariyani3001**
## Commit Summary
[90cf4cb](https://github.com/Swarnendu0123/kbs-website/pull/21/commits/90cf4cb28260701b324627869dc236ff50913ef9) Firebase Login Signup and Logout
[e5267b9](https://github.com/Swarnendu0123/kbs-website/pull/21/commits/e5267b96b5862367c6c493a87f432e1cd81f9440) Small changes

## File Changes ([8 files](https://github.com/Swarnendu0123/kbs-website/pull/21/files))
M [.gitignore](https://github.com/Swarnendu0123/kbs-website/pull/21/files#diff-bc37d034bad564583790a46f19d807abfe519c5671395fd494d8cce506c42947) (1)
M [package-lock.json](https://github.com/Swarnendu0123/kbs-website/pull/21/files#diff-053150b640a7ce75eff69d1a22cae7f0f94ad64ce9a855db544dda0929316519) (692)
M [package.json](https://github.com/Swarnendu0123/kbs-website/pull/21/files#diff-7ae45ad102eab3b6d7e7896acd08c427a9b25b346470d7bc6507b6481575d519) (1)
A [src/components/authentication/FirebaseConfig.js](https://github.com/Swarnendu0123/kbs-website/pull/21/files#diff-bedfc7c52b918ef02c201663455d2b36e54620752d26a08fb7777d89842831bd) (20)
M [src/components/authentication/sign-in.component.jsx](https://github.com/Swarnendu0123/kbs-website/pull/21/files#diff-47bac078e08510e69e4c416d1ef2a13b8cfd9134885f6747eb3f54f37e707ade) (87)
M [src/components/authentication/sign-up.component.jsx](https://github.com/Swarnendu0123/kbs-website/pull/21/files#diff-02bf202024e437abafd65db39dd777184caa03498b2335e5c56b32867da2c3ad) (106)
M [src/components/home/Home.component.jsx](https://github.com/Swarnendu0123/kbs-website/pull/21/files#diff-6dc467b1bca211240471527cbdde8013dfd0d0fde604c9840b14713ff040c2a6) (4)
M [src/components/navAndFooter/nav-and-footer.component.jsx](https://github.com/Swarnendu0123/kbs-website/pull/21/files#diff-7dc92c6da34fa86a259c13c0345e62882b48003e84047c19ec812d9948d05a51) (104)

## Patch Links:
https://github.com/Swarnendu0123/kbs-website/pull/21.patch
https://github.com/Swarnendu0123/kbs-website/pull/21.diff

### CODE REVIEW

**Comment by Swarnendu0123** [comment]
Can you please attach one video demonstration of your implementation.

**Comment by Parth-Hariyani3001** [comment]
Actually I don't have much idea about conflicts, some help would be appreciated and I'll post the video by tomorrow

**Comment by Parth-Hariyani3001** [comment]
Link to the video : https://youtu.be/XZhMUaA9As8

**Comment by Swarnendu0123** [comment]
> Link to the video : https://youtu.be/XZhMUaA9As8

Looks good, you explained everything, what you have done. But I was asking you to show one sign-up and sign-in and logout. Additionally, the data is actually going to firebase. It would be very helpful for me to verify your PR.

**Comment by Swarnendu0123** [comment]
Thanks for working on this!! our website now have login feature.

**Pull request merged**
