### PR TITLE
Error 404 Page Added

### LINKED ISSUE #17: Implementation of `404:Not Found` page
# Details:
- Use [Preline](https://preline.co/examples/layouts-miscellaneous.html) to get the page
-  Use only dark mode for implementing the UI
- Add one component and route

## Screenshot
- It should look like
Screenshot (72)

### PR DESCRIPTION
**Pull request by Parth-Hariyani3001**
This Changes resolves #17 by adding NotFound Componet that acts as an error 404 page

### CODE REVIEW

**Comment by Swarnendu0123** [comment]
Replace the 404 and the text colour to white.
And don't use blue colour, we are using green as our primary colour. Change the colour to that specific green colour which was used.

**Comment by Parth-Hariyani3001** [comment]
make it green like the button?

**Comment by Swarnendu0123** [comment]
Not like buttons just change the colour from blue to green.

**Comment by Swarnendu0123** [comment]
Thanks @Parth-Hariyani3001 for working on this, I hope you will actively contribute to this repo from now. Welcome to the KBS community. I am going to merge it for now. Well done!!

**Comment by Parth-Hariyani3001** [comment]
This was my first contribution, thanks for the assistance, will try to contribute as much as possible.

**Pull request merged**
